# Generated by Django 5.2 on 2025-05-05 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        help_text="12-digit alphanumeric customer ID",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Customer ID must be exactly 12 alphanumeric characters.",
                                regex="^[A-Za-z0-9]{12}$",
                            )
                        ],
                        verbose_name="customer ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Format: DD-MM-YYYY",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "customer metadata",
                "verbose_name_plural": "customer metadata",
            },
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="users.customermetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "view history",
                "verbose_name_plural": "view histories",
            },
        ),
        migrations.CreateModel(
            name="BookmarkedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("bookmarked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_products",
                        to="users.customermetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmarked product",
                "verbose_name_plural": "bookmarked products",
                "unique_together": {("customer", "product_id")},
            },
        ),
    ]
