# Generated by Django 5.2 on 2025-07-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductCategory",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="ProductCompany",
            new_name="Company",
        ),
    ]
