# Generated by Django 5.2 on 2025-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_company_category_company_products_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_desc", models.TextField(max_length=5000)),
            ],
            options={
                "verbose_name_plural": "about",
            },
        ),
    ]
