# Generated by Django 5.2 on 2025-04-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_about"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="customers",
            options={"verbose_name_plural": "customers"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name_plural": "Sub Categories"},
        ),
    ]
