# Generated by Django 5.2 on 2025-05-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_delete_about_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="mobile_no",
        ),
    ]
