# Generated by Django 5.2 on 2025-05-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_customers_mobile_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customers",
        ),
    ]
