# Generated by Django 5.2 on 2025-05-07 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customermetadata",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customermetadata",
            name="user",
        ),
        migrations.AddField(
            model_name="customermetadata",
            name="email",
            field=models.EmailField(default="test@gmail.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customermetadata",
            name="password",
            field=models.CharField(default="text password", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customermetadata",
            name="customer_id",
            field=models.CharField(
                help_text="12-digit alphanumeric customer ID",
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Customer ID must be exactly 12 alphanumeric characters.",
                        regex="^[A-Za-z0-9]{12}$",
                    )
                ],
                verbose_name="customer ID",
            ),
        ),
        migrations.AlterField(
            model_name="customermetadata",
            name="date_of_birth",
            field=models.DateField(
                help_text="Format: YYYY-MM-DD", verbose_name="date of birth"
            ),
        ),
        migrations.AlterField(
            model_name="customermetadata",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
    ]
